name: BeterBed
main: nl.wiselan.beterbed.Main
api-version: 1.13
version: 1.2
author: Wouter Wijsman AKA sharkwouter
website: https://github.com/sharkwouter/BeterBed
description: This plugin allows you to set a bed as your spawn point during the day and it makes sleeping heal your character
commands: 